### ISSUE TITLE
No handlers could be found

### ISSUE THREAD

**Issue by Jbithell** [pavoni/pyloopenergy#14]
I'm getting an error: `No handlers could be found for logger "pyloopenergy.loop_energy"`
```
Exception in thread LoopEnergy Event Thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/pyloopenergy/loop_energy.py", line 165, in _run_event_thread
    LOG.debug('LoopEnergy thread poll')
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 215, in __exit__
    self.disconnect()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 299, in disconnect
    namespace.on_disconnect()
  File "build/bdist.linux-x86_64/egg/pyloopenergy/loop_energy.py", line 123, in on_disconnect
    self.terminate()
  File "build/bdist.linux-x86_64/egg/pyloopenergy/loop_energy.py", line 230, in terminate
    self._event_thread.join()
  File "/usr/lib/python2.7/threading.py", line 931, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

**Comment by pavoni** [comment]
Looks like this may be a solution - will try when I have some time http://excid3.com/blog/no-handlers-could-be-found-for-logger

**Comment by Jbithell** [comment]
Yep that fixes it! Thanks so much
---
**Solution:** append code below to top of file calling pyloopenergy script
```
import logging
logging.basicConfig()
```
