### ISSUE TITLE
Exception after long run kills monitor thread.

### ISSUE THREAD

**Issue by pavoni** [pavoni/pyloopenergy#15]
````
WARNING:socketIO_client:[connection error] connection closed (Connection is already closed.)
WARNING:socketIO_client:www.your-loop.com:443/socket.io/1: [connection error] connection closed (Connection is already closed.)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.your-loop.com
Exception in thread LoopEnergy Event Thread:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/pyloopenergy/loop_energy.py", line 165, in _run_event_thread
    LOG.debug('LoopEnergy thread poll')
  File "/usr/local/lib/python3.5/site-packages/socketIO_client/__init__.py", line 215, in __exit__
    self.disconnect()
  File "/usr/local/lib/python3.5/site-packages/socketIO_client/__init__.py", line 294, in disconnect
    self._transport.disconnect(path)
  File "/usr/local/lib/python3.5/site-packages/socketIO_client/__init__.py", line 320, in _transport
    socketIO_session = self._get_socketIO_session()
  File "/usr/local/lib/python3.5/site-packages/socketIO_client/__init__.py", line 348, in _get_socketIO_session
    self.is_secure, self._base_url, **self._kw)
  File "/usr/local/lib/python3.5/site-packages/socketIO_client/__init__.py", line 522, in _get_socketIO_session
    heartbeat_timeout=int(response_parts[1]),
ValueError: invalid literal for int() with base 10: '100%;\n            background'
````

**Comment by Jbithell** [comment]
Sadly this exception came up again today on a thread running a few days 
```
WARNING:socketIO_client:[connection error] connection closed (Connection is already closed.)
WARNING:socketIO_client:www.your-loop.com:443/socket.io/1: [connection error] connection closed (Connection is already closed.)
Exception in thread LoopEnergy Event Thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyloopenergy-0.0.13-py2.7.egg/pyloopenergy/loop_energy.py", line 165, in _run_event_thread
    LOG.debug('LoopEnergy thread poll')
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 215, in __exit__
    self.disconnect()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 294, in disconnect
    self._transport.disconnect(path)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 320, in _transport
    socketIO_session = self._get_socketIO_session()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 348, in _get_socketIO_session
    self.is_secure, self._base_url, **self._kw)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 522, in _get_socketIO_session
    heartbeat_timeout=int(response_parts[1]),
ValueError: invalid literal for int() with base 10: '100%;             background'

```

**Comment by pavoni** [comment]
@Jbithell Is it possible you're running an old version?

Looking at the line number of the python trace - that code is now on line 166 rather than 165 (it was on line 165 in older versions).

The latest version of the library catches that `ValueError` and reconnects - so would be surprised if that still goes wrong.
