### ISSUE TITLE
Exception in thread LoopEnergy Event Thread

### ISSUE THREAD

**Issue by DJBenson** [pavoni/pyloopenergy#17]
I've tried running the sample code and am getting;

`Exception in thread LoopEnergy Event Thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/pyloopenergy/pyloopenergy/loop_energy.py", line 134, in _run_event_thread
    Namespace) as socket_io:
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
StopIteration`

**Comment by pavoni** [comment]
Glad you found it - was going to investigate tomorrow - so thanks for the detective irk.
