### ISSUE TITLE
Unknown Exception

### ISSUE THREAD

**Issue by Jbithell** [pavoni/pyloopenergy#24]
```
Exception in thread LoopEnergy Event Thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyloopenergy-0.0.13-py2.7.egg/pyloopenergy/loop_energy.py", line 133, in _run_event_thread
    Namespace) as socket_io:
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 206, in __init__
    self.define(Namespace)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 223, in define
    namespace = Namespace(self._transport, path)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 320, in _transport
    socketIO_session = self._get_socketIO_session()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 348, in _get_socketIO_session
    self.is_secure, self._base_url, **self._kw)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client-0.5.6-py2.7.egg/socketIO_client/__init__.py", line 522, in _get_socketIO_session
    heartbeat_timeout=int(response_parts[1]),
ValueError: invalid literal for int() with base 10: '100%;             background'

Exception ValueError: ValueError("invalid literal for int() with base 10: '100%;             background'",) in <bound method SocketIO.__del__ of <socketIO_client.SocketIO object at 0x7f842e7323d0>> ignored

```

**Comment by Jbithell** [comment]
Came up today at boot

**Comment by pavoni** [comment]
Your stack traces indicate you're running `0.0.13`

Current version is `0.0.16`

I think I fixed that bug in `0.0.14`

**Comment by Jbithell** [comment]
`git pull` returns `Already up-to-date.` - how do I update?

**Comment by pavoni** [comment]
I don't think you're running the version from git.

Probably a pip install version so try something like `pip install pyloopenergy --upgrade `

**Comment by Jbithell** [comment]
Ah of course! Me being stupid again - I've updated and everything seems well so far!

**Comment by pavoni** [comment]
👍 No problem. 

I still think there are some more exceptions I need to catch - so let me know if it goes wrong again.

I plan to take a look at https://github.com/pavoni/pyloopenergy/issues/23 this weekend...
