### ISSUE TITLE
Exception in LoopEnergy Event Thread

### ISSUE THREAD

**Issue by Jbithell** [pavoni/pyloopenergy#26]
```
Exception in thread LoopEnergy Event Thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyloopenergy/loop_energy.py", line 134, in _run_event_thread
    Namespace) as socket_io:
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 353, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 54, in __init__
    self._transport
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 62, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 76, in _get_engineIO_session
    transport.recv_packet())
StopIteration

```

This seems to be happening if the script is left running for a while - any ideas?

**Comment by pavoni** [comment]
I've steadily been adding to the list of exceptions that I catch and then try and restart the connection.

Afraid I'm tied up for the next couple of weeks - but if you want to try a fix take a look here and perhaps add the exception. https://github.com/pavoni/pyloopenergy/blob/master/pyloopenergy/loop_energy.py#L168

If it works please send a PR!

I'm running my setup on Python 3 - which perhaps behaves very slightly differently as I don't see this.

**Comment by BenWoodford** [comment]
This appears to be 3.5/3.6 related, and handling that exception will just cause a loop.

I'm working on a fix and will PR shortly.

**Comment by pavoni** [comment]
Catching the exception and setting `self.reconnect_needed = True` _should_ just close the socket and try to re-connect.

If you turn up the log level you should see some messages about trying to reconnect.

If it's looping it may be worth seeing if the connect is returning some sort of useful error.

**Comment by BenWoodford** [comment]
Yeah, it just looped reconnecting when I tried it.

If you’d like a replicated environment, I’m doing this within the latest dev tag of the Home Assistant docker container, and running the code found here: https://github.com/home-assistant/home-assistant/issues/8137#issuecomment-346946710

**Comment by pavoni** [comment]
Should be fixed by https://github.com/pavoni/pyloopenergy/pull/28
