### ISSUE TITLE
TypeError: cafile, capath and cadata cannot be all omitted

### ISSUE THREAD

**Issue by spants** [pavoni/pyloopenergy#27]
seem to be having an issue connecting, not sure what has changed...
(downloaded the latest version)

Exception in thread LoopEnergy Event Thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/boot/config/plugins/loop2mqtt/pyloopenergy/loop_energy.py", line 134, in _run_event_thread
    Namespace) as socket_io:
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 206, in __init__
    self.define(Namespace)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 223, in define
    namespace = Namespace(self._transport, path)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 333, in _transport
    socketIO_session, self._transport_name)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 381, in _get_transport
    }[transport_name](session, self.is_secure, self._base_url, **self._kw)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/transports.py", line 147, in __init__
    self._connection = websocket.create_connection(url, header=headers)
  File "/usr/lib64/python2.7/site-packages/websocket/_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "/usr/lib64/python2.7/site-packages/websocket/_core.py", line 211, in connect
    options.pop('socket', None))
  File "/usr/lib64/python2.7/site-packages/websocket/_http.py", line 77, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/usr/lib64/python2.7/site-packages/websocket/_http.py", line 182, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/usr/lib64/python2.7/site-packages/websocket/_http.py", line 138, in _wrap_sni_socket
    context.load_verify_locations(cafile=sslopt.get('ca_certs', None), capath=sslopt.get('ca_cert_path', None))
TypeError: cafile, capath and cadata cannot be all omitted

**Comment by pavoni** [comment]
A couple of years old - so closing this - please re-open if needed.
