### ISSUE TITLE
division by zero for gas useage

### ISSUE THREAD

**Issue by spants** [pavoni/pyloopenergy#6]
The period calculation is causing problems:

Period is calculated as 0 - is this line correct:
       period = (self.gas_device_timestamp - self.gas_old_timestamp)/(60*60)

variables:
('Electricity =', 1.0)
('Gas Used =', 80)
('self.gas_device_timestamp =', 1460049300)
('self.gas_old_timestamp =', 1460048400)
('period =', 0)

error:
Exception in thread LoopEnergy Event Thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/boot/config/plugins/hive2mqtt/pyloopenergy/loop_energy.py", line 134, in _run_event_thread
    socket_io.wait(seconds=15)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 252, in wait
    self._process_events(timeout)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 271, in _process_events
    self._process_packet(packet)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 279, in _process_packet
    delegate(packet, namespace._find_event_callback)
  File "/usr/lib64/python2.7/site-packages/socketIO_client/__init__.py", line 444, in _on_event
    find_event_callback(event)(*args)
  File "/boot/config/plugins/hive2mqtt/pyloopenergy/loop_energy.py", line 190, in _update_gas
    self.gas_kw = (CONVERSION_FACTOR * gas_used / period)/1000
ZeroDivisionError: float division by zero

**Comment by pavoni** [comment]
Looks like there was a change between Python 2 and 3 about how integer division works.

Will push a fix tomorrow - thanks for the report.
